### ISSUE TITLE
Not being able to require from composer

### ISSUE THREAD

**Issue by luciojb** [selective-php/xmldsig#1]
Salutations!

I was trying to use your library to sign some XML files in my project, but unfortunately i could not require it from composer, which gave me the message:

```
[InvalidArgumentException]                                                                           
  Could not find a matching version of package selective/xmldsig. Check the package spelling, 
your version constraint and that the package is available in a stability which matches your 
minimum-stability (stable). 
```

So, i had to actually clone it. I never published a package to composer and such, so idk why this happens, so if you could publish it i would be happy, or if it's published, update your readme with the correct package name =).

I didn't test the library yet, hope it will be useful for my project.
Best regards,

Lúcio.

**Comment by odan** [comment]
Hi @luciojb I will publish this package now.

**Comment by odan** [comment]
This package is now available.
