### ISSUE TITLE
Possibility to verify digitalsign with public key without "password".

### ISSUE THREAD

**Issue by ArmenMelk** [selective-php/xmldsig#10]
Is that possible to verify digital sign key without "password".
With x509 standards they don't need to have "password" for verify digital signature with public key.
How we can modify validator for support that?

**Comment by odan** [comment]
There was a copy/paste typo in the readme. 

This has been fixed now. See [here](https://github.com/selective-php/xmldsig#verify-the-digital-signatures-of-xml-documents)

```php
// or load a public key file (without password)
$signatureValidator->loadPublicKeyFile('cacert.pem');

// or load the public key from a string (without password)
$signatureValidator->loadPublicKey('public key content');
```
