### ISSUE TITLE
Installing latest version on PHP 7.4

### ISSUE THREAD

**Issue by iBullRay** [selective-php/xmldsig#17]
Hello,
Cant install your latest version on PHP 7.4 website. Downloading only version 2.2 with composer
Anyway, it works on PHP 7.4 version without installing via composer

`Problem 1
    - Installation request for selective/xmldsig ^2.3 -> satisfiable by selective/xmldsig[2.3.0].
    - selective/xmldsig 2.3.0 requires php ^8.0 -> your PHP version (7.4.3) does not satisfy that requirement.
`
Can you set minimal version to 7.0?

**Comment by odan** [comment]
I just reimplemented the support for PHP 7.4. Please try to install the latest version with composer.

**Comment by iBullRay** [comment]
Composer downloading old 2.2.1 version
Will wait and try again
