### ISSUE TITLE
x509data

### ISSUE THREAD

**Issue by pablitouy** [selective-php/xmldsig#19]
this dont apears

what can i do ?

<KeyInfo>
<X509Data>
<X509Certificate>

**Comment by odan** [comment]
I don't understand this question.

**Comment by pablitouy** [comment]
this is my xml

<DAE xmlns="http://www.aduanas.gub.uy/LUCIA/DAE"><TipoDocumento>4</TipoDocumento><IdDocumento>210239830016</IdDocumento><FechaHoraDocumentoElectronico>2022-04-05T16:59:33</FechaHoraDocumentoElectronico><CodigoIntercambio>WS_PEDIDOCANAL</CodigoIntercambio><NroTransaccion>040516593398</NroTransaccion><Objeto><DUAAduana>001</DUAAduana><DUAAno>2022</DUAAno><DUANumero>061750</DUANumero></Objeto><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>wfp1G6aoOrUw/+h+9RNMhcrHZZ8=</DigestValue></Reference></SignedInfo><SignatureValue>H6cfowwuuKSh+eIuKgdPaxRrjJex8/zIt5ibK28myKe1eAtHrtXFDCfXdRF4sWarEztcpzW+xO0KhCjBMGX+xTK99VKHPgMaHzmidtWWVeF4kzOC1glcdfUxR9swt5AM26Z4slReMmPlXGpcWTbHJwpkGz1kqS/w+RmBqCYZHsie7wQFG87SJBVUG5IFOHX07HFzn4c14TcffI9wmOSle4/YRjIkcS4gw09pluS2If0x3VkDWfV/UlhIbnZ8papT0ncDGP/Nf9mAaCv/vQckI4Bkk5PT65Ss4Wz44BCePNByHQ1paN5fWatLwc8ABh5o73UOfK4Q0rB4nv6rV3UM2A==</SignatureValue><KeyInfo><KeyValue><RSAKeyValue><Modulus>wublVRnHPouzxhcySLmuLW3INX6RnFyCnGCmInoyQNN4Zmuf7DsLCi2uwK+vjKBMQuezyuB4rwL1hfUVPDc72eFLSQ6EMtt4D3TB31Lrz3gRCL0XldbKxeycFCiWt26YDE7t2U4u9zzocaJpmNJ9U/kdKn9JKfT7gL8hoXGXhKlmfS9+82BhD/u5SSjF/PqrSirtILfs0g53xJTHd41be6B+4R97q2ZRhxiUreTG9inysGgEu3clytIi4i+8SyVbwR6rhj744g0+T2rDwOxr2Rbg/9jDTI/349XvPKqxAJx7TppVpWJLqk+UO3kHrhoTC0UlzAPxyTverI0KmJrlTw==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue></KeyValue></KeyInfo></Signature></DAE>

i need this node ids miising (      <KeyInfo><X509Data><X509Certificate>    )

<DAE xmlns="http://www.aduanas.gub.uy/LUCIA/DAE"><TipoDocumento>4</TipoDocumento><IdDocumento>210239830016</IdDocumento><FechaHoraDocumentoElectronico>2022-04-05T16:59:33</FechaHoraDocumentoElectronico><CodigoIntercambio>WS_PEDIDOCANAL</CodigoIntercambio><NroTransaccion>040516593398</NroTransaccion><Objeto><DUAAduana>002</DUAAduana><DUAAno>2022</DUAAno><DUANumero>061472</DUANumero></Objeto><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>cLsKiuqC3W687MvBZ3tFhwL/ZFM=</DigestValue></Reference></SignedInfo><SignatureValue>JK0Q9zHJRbppx3dQDQRjRWc1XC6/RR2kvbs8T+u8i6uzJDNo647T3Ai7xkQ5XuonYpu6+cD10TuproOKqDA0Shj61GrYwBcbtKSX5W5C3UPzf0kBGp5jiYCgLaNhQoH5sxCJFxSLFfgEj4WJxtCeHOxKqDMzj5OH666GS+KnmHZ1kRHAOcTJX1PM2B39qwppEkhP9qlvGch16H3uKJmVAnRRNPBR+j07nLJkk9cH9yJsbf0od3cfAXBUGkwBKqxPGQ7+D3+pxxqDO33HpsMZ1q6D8n41arDGY32Htm/FWAwEPSG99nMPRPtaVyWQH2EqZRw0DfusIIllyMPYntQdqA==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIGNzCCBB+gAwIBAgIUKGNjYqQrbTQ58yeCNVjTh45dJgYwDQYJKoZIhvcNAQELBQAwWjEdMBsGA1UEAxMUQ29ycmVvIFVydWd1YXlvIC0gQ0ExLDAqBgNVBAoMI0FkbWluaXN0cmFjacOzbiBOYWNpb25hbCBkZSBDb3JyZW9zMQswCQYDVQQGEwJVWTAeFw0yMTAzMDQyMDQ0MjRaFw0yMzAzMDQyMDQ0MjRaMGMxHDAaBgNVBAMME0dPTlpBTEVaIFkgQ0lBIExUREExHDAaBgNVBAoME0dPTlpBTEVaIFkgQ0lBIExUREExCzAJBgNVBAYTAlVZMRgwFgYDVQQFEw9SVUMyMTAyMzk4MzAwMTYwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDC5uVVGcc+i7PGFzJIua4tbcg1fpGcXIKcYKYiejJA03hma5/sOwsKLa7Ar6+MoExC57PK4HivAvWF9RU8NzvZ4UtJDoQy23gPdMHfUuvPeBEIvReV1srF7JwUKJa3bpgMTu3ZTi73POhxommY0n1T+R0qf0kp9PuAvyGhcZeEqWZ9L37zYGEP+7lJKMX8+qtKKu0gt+zSDnfElMd3jVt7oH7hH3urZlGHGJSt5Mb2KfKwaAS7dyXK0iLiL7xLJVvBHquGPvjiDT5PasPA7GvZFuD/2MNMj/fj1e88qrEAnHtOmlWlYkuqT5Q7eQeuGhMLRSXMA/HJO96sjQqYmuVPAgMBAAGjggHqMIIB5jAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFGzisCaNW9YmCB+YXWngDn9V7K52MHkGCCsGAQUFBwEBBG0wazA2BggrBgEFBQcwAoYqaHR0cDovL2FuY2NhLmNvcnJlby5jb20udXkvYW5jY2EvYW5jY2EuY2VyMDEGCCsGAQUFBzABhiVodHRwOi8vYW5jY2EuY29ycmVvLmNvbS51eS9hbmNjYS9PQ1NQMIG4BgNVHSAEgbAwga0wZAYLYIZahOKuHYSIBQQwVTBTBggrBgEFBQcCARZHaHR0cDovL3VjZS5ndWIudXkvaW5mb3JtYWNpb24tdGVjbmljYS9wb2xpdGljYXMvY3BfcGVyc29uYV9qdXJpZGljYS5wZGYwRQYLYIZahOKuHYSIBQYwNjA0BggrBgEFBQcCARYoaHR0cDovL2FuY2NhLmNvcnJlby5jb20udXkvYW5jY2EvY3BzLnBkZjATBgNVHSUEDDAKBggrBgEFBQcDAjA7BgNVHR8ENDAyMDCgLqAshipodHRwOi8vYW5jY2EuY29ycmVvLmNvbS51eS9hbmNjYS9hbmNjYS5jcmwwHQYDVR0OBBYEFD99t9+FGdKEyvvY+/ckwJOIKpeLMA4GA1UdDwEB/wQEAwIE8DANBgkqhkiG9w0BAQsFAAOCAgEAcRMOnvc11sy9u9VuDLjCh23kK72dc0rBC/RQUzpERqbhP9cmQhGhtBxVgN2g5FK3VX4UdCr4lSn+yhHY0l9TYLnQ6rb81VVozC2GVIaDpoInV6412F8Xu85r14NnJoRxGJShDVq/XuhJFn79IDV6zQ5kIH4AUM4MRzWkuLhHukPe5GQKIYqgMI9ojQ6Jikz+cy6ysjalYFk/2vPk5AL07HeS3rQuIH3QUARM4rSUOS4GtZ+Vv4Z0h2MWVhvudPcFyFHNkmnTw3YBTlolAaA0B335pU7il7Qy8wyaGeIURaEHpCEv2Pp+FKFpjXI/x/eSCWlH7/0EpBmqjADVn4qmg1CwkUhLqiYtLG99nzXQ0xBJcaNqVOkI5BaJFnakdi97VqGpWm97L1xWc5cg3Lf1mEUip0fD9jPliL2j1RSqQPJiwQC1ZP8Kn+iJg+egjiVafy9VUv9AtHEkc04jRK7/3w726AKbJAGgo/l0ndsfG0+aUkzaOpaLrYmuYH4Na6bbZoYMEyXB4wnQWHMa+wRkyDh8fQxodh4ybq5yPFNLZep2gilifJaoi5hpgLnDE/4ugPL8Idfvj6Q4bb7gauNSSxL99CnoKFK4WTB805JIjUuzdR1YLy7dJtwTsy6XGcs9S9qA1quvnYgOYw+J3XM4EXynH6zov80Xz13D1q+Jnkc=</X509Certificate></X509Data></KeyInfo></Signature></DAE>

**Comment by pablitouy** [comment]
this node are missing
`<KeyInfo><X509Data><X509Certificate>`

**Comment by odan** [comment]
The [X509Data](https://lists.w3.org/Archives/Public/public-xmlsec-maintwg/2007Jun/att-0068/DNAMES_Section4.4.4.htm) element is not supported. Feel free to create a PR.
