### ISSUE TITLE
DigestValue and SignatureValue are different from SoapUI values

### ISSUE THREAD

**Issue by yamenarahman** [selective-php/xmldsig#20]
I'm facing a weird issue, I'm able to connect to the Soap service through SoapUI and send successful requests, here is the ws settings in SoapUI:
<img width="808" alt="Screen Shot 2022-04-12 at 11 36 52 AM" src="https://user-images.githubusercontent.com/24607365/162930760-737d3abd-d378-4a6e-8041-8dfb20bf7dcf.png">

However when using this library I can NOT generate the same digest or signature as SoapUI generates them.
```php
$xmlSigner = new XmlSigner();
$xmlSigner->loadPrivateKeyFile('path-to-private-key', '');
$xmlSigner->setReferenceUri('random-id');
$xmlSigner->signXml('<soapenv:Body>....</soapenv:Body>', DigestAlgorithmType::SHA1);
 // The resulting digest is different from SoapUI, and result soap error Hash values do not match
```

Any idea what I'm missing here?

**Comment by odan** [comment]
I guess this is not supported. You can try to sign the full SOAP message using the root element. 
Otherwise try to use the `robrichards/xmlseclibs` instead.

Here is an example of how to sign a SOAP message:

https://gist.github.com/odan/e1c2f839315215194b01e6cf70eb8613

**Comment by yamenarahman** [comment]
It was about the prefix list, the prefix list affects directly the hash values, so I had to specify the prefix list while canonicalization:
```php
// DOMNode 
$object->C14N(true, false, null, ['soapenv', '.. any other prefixes']); //
```
