### ISSUE TITLE
how to sign XML with x509 certificate

### ISSUE THREAD

**Issue by AhmedKhan891** [selective-php/xmldsig#21]
Hi,

i want to sign xml using 509 certificate and hash it but I am not getting a proper answer for the same

**Comment by odan** [comment]
Not sure what you mean with proper answer when there is no proper question.

**Comment by AhmedKhan891** [comment]
Sorry my bad.

1.) I want to sign an XML Document with x509 Certificate and Hash it with SHA256 The ECDSA Algorithm.
2.) how to generate digest value in XML File and encoded in base 64

Here is a completed example and we are trying to do this

<ext:UBLExtensions>
    <ext:UBLExtension>
        <ext:ExtensionURI>urn:oasis:names:specification:ubl:dsig:enveloped:xades</ext:ExtensionURI>
        <ext:ExtensionContent>
            
            <sig:UBLDocumentSignatures xmlns:sig="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2" xmlns:sac="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2" xmlns:sbc="urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2">
                <sac:SignatureInformation>
                    <cbc:ID>urn:oasis:names:specification:ubl:signature:1</cbc:ID>
                    <sbc:ReferencedSignatureID>urn:oasis:names:specification:ubl:signature:Invoice</sbc:ReferencedSignatureID>
                    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="signature">
                        <ds:SignedInfo>
                            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
                            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"/>
                            <ds:Reference Id="invoiceSignedData" URI="">
                                <ds:Transforms>
                                    <ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
                                        <ds:XPath>not(//ancestor-or-self::ext:UBLExtensions)</ds:XPath>
                                    </ds:Transform>
                                    <ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
                                        <ds:XPath>not(//ancestor-or-self::cac:Signature)</ds:XPath>
                                    </ds:Transform>
                                    <ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
                                        <ds:XPath>not(//ancestor-or-self::cac:AdditionalDocumentReference[cbc:ID='QR'])</ds:XPath>
                                    </ds:Transform>
                                    <ds:Transform Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
                                </ds:Transforms>
                                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                                <ds:DigestValue>WI6GNwty4XrTc3P1WrRM1xlhqz9TimXdCLH9sgmj0Sg=</ds:DigestValue>
                            </ds:Reference>
                            <ds:Reference Type="http://www.w3.org/2000/09/xmldsig#SignatureProperties" URI="#xadesSignedProperties">
                                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                                <ds:DigestValue>ZjU2ZjM4YTExODRmNzE0ZjIxODA4MDYxYjhiMzdmM2JlMTJiNWQ0N2E2YjhjNzQwMjg2NDBkMzJlM2MxNjM2Nw==</ds:DigestValue>
                            </ds:Reference>
                        </ds:SignedInfo>
                        <ds:SignatureValue>MEUCIQCCGL7AJacVObs7luFYTbsqKr9qLZX+LYjZivOjDNnaYgIgT0SrZZKk3L8fzV8/J7h9p7wH0BoqplW0RBcWOVNeW0w=</ds:SignatureValue>
                        <ds:KeyInfo>
                            <ds:X509Data>
                                <ds:X509Certificate>MIID6TCCA5CgAwIBAgITbwAAf8tem6jngr16DwABAAB/yzAKBggqhkjOPQQDAjBjMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNnb3YxFzAVBgoJkiaJk/IsZAEZFgdleHRnYXp0MRwwGgYDVQQDExNUU1pFSU5WT0lDRS1TdWJDQS0xMB4XDTIyMDkxNDEzMjYwNFoXDTI0MDkxMzEzMjYwNFowTjELMAkGA1UEBhMCU0ExEzARBgNVBAoTCjMxMTExMTExMTExDDAKBgNVBAsTA1RTVDEcMBoGA1UEAxMTVFNULTMxMTExMTExMTEwMTExMzBWMBAGByqGSM49AgEGBSuBBAAKA0IABGGDDKDmhWAITDv7LXqLX2cmr6+qddUkpcLCvWs5rC2O29W/hS4ajAK4Qdnahym6MaijX75Cg3j4aao7ouYXJ9GjggI5MIICNTCBmgYDVR0RBIGSMIGPpIGMMIGJMTswOQYDVQQEDDIxLVRTVHwyLVRTVHwzLWE4NjZiMTQyLWFjOWMtNDI0MS1iZjhlLTdmNzg3YTI2MmNlMjEfMB0GCgmSJomT8ixkAQEMDzMxMTExMTExMTEwMTExMzENMAsGA1UEDAwEMTEwMDEMMAoGA1UEGgwDVFNUMQwwCgYDVQQPDANUU1QwHQYDVR0OBBYEFDuWYlOzWpFN3no1WtyNktQdrA8JMB8GA1UdIwQYMBaAFHZgjPsGoKxnVzWdz5qspyuZNbUvME4GA1UdHwRHMEUwQ6BBoD+GPWh0dHA6Ly90c3RjcmwuemF0Y2EuZ292LnNhL0NlcnRFbnJvbGwvVFNaRUlOVk9JQ0UtU3ViQ0EtMS5jcmwwga0GCCsGAQUFBwEBBIGgMIGdMG4GCCsGAQUFBzABhmJodHRwOi8vdHN0Y3JsLnphdGNhLmdvdi5zYS9DZXJ0RW5yb2xsL1RTWkVpbnZvaWNlU0NBMS5leHRnYXp0Lmdvdi5sb2NhbF9UU1pFSU5WT0lDRS1TdWJDQS0xKDEpLmNydDArBggrBgEFBQcwAYYfaHR0cDovL3RzdGNybC56YXRjYS5nb3Yuc2Evb2NzcDAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMDMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwIwCgYIKwYBBQUHAwMwCgYIKoZIzj0EAwIDRwAwRAIgOgjNPJW017lsIijmVQVkP7GzFO2KQKd9GHaukLgIWFsCIFJF9uwKhTMxDjWbN+1awsnFI7RLBRxA/6hZ+F1wtaqU</ds:X509Certificate>
                            </ds:X509Data>
                        </ds:KeyInfo>
                        <ds:Object>
                            <xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" Target="signature">

**Comment by AhmedKhan891** [comment]
Any help?

**Comment by odan** [comment]
The documentation in the README contains such an example. Have you tried this first?

**Comment by AhmedKhan891** [comment]
we tried but we are not getting the proper hash key. we need to sign the xml using x509 in csr format. since we have less knowledge related to xml maybe that is one of the reason we are not able to sign it properly. any help is appreciated you can also reach me at my email mohammadahmed891@gmail.com

**Comment by AhmedKhan891** [comment]
this xades signed properties we signed the hash above correctly now this is is something we could not solve

<ds:Reference Type="http://www.w3.org/2000/09/xmldsig#SignatureProperties" URI="#xadesSignedProperties">
<ds:DigestMethod Algorithm="[http://www.w3.org/2001/04/xmlenc#sha256"/>](http://www.w3.org/2001/04/xmlenc#sha256%22/%3E)
ds:DigestValueZjU2ZjM4YTExODRmNzE0ZjIxODA4MDYxYjhiMzdmM2JlMTJiNWQ0N2E2YjhjNzQwMjg2NDBkMzJlM2MxNjM2Nw==</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
ds:SignatureValueMEUCIQCCGL7AJacVObs7luFYTbsqKr9qLZX+LYjZivOjDNnaYgIgT0SrZZKk3L8fzV8/J7h9p7wH0BoqplW0RBcWOVNeW0w=</ds:SignatureValue>

**Comment by odan** [comment]
The ECDSA (Elliptic Curve) algorithm is not supported by this library. It is also not planned to support ECDSA in the future.

**Comment by thaifanisalla** [comment]
@AhmedKhan891   if you success in a sign xml 
then please show the method here

**Comment by LordOfTheRats** [comment]
Hi,

I am currently working on this feature. See https://github.com/selective-php/xmldsig/pull/22.

I am not very familiar with XMLDSig, so let me know if something is not up to spec.

**Comment by AhmedKhan891** [comment]
x509 certificate is a compliance api response token.  To get the x509
certificate we need to decode token

Base64 decode

**Comment by odan** [comment]
X509 and ECDSA will be available in the next major version.

Please read the new README, test the latest dev version and give me feedback.

```
composer require selective/xmldsig dev-master
```

**Comment by odan** [comment]
Any feedback?
