### ISSUE TITLE
status

### ISSUE THREAD

**Issue by cognitus** [selective-php/xmldsig#25]
I want to know if this proyect is abandoned, because on packagist appears abandoned.

**Comment by odan** [comment]
My impression was that [robrichards/xmlseclibs](https://packagist.org/packages/robrichards/xmlseclibs) provides more features and a larger community. Some people also have such special requirements that cannot be provided in a generic package. So they implemented their own solution.
On the other hand, the last release of robrichards/xmlseclibs was in April 2022. Is this package still maintained?
What do you think about it? Is it reasonable to maintain two similar packages for this use case?

I would be happy to hear your opinion.
