### ISSUE TITLE
setReferenceURI

### ISSUE THREAD

**Issue by jlaraf81** [selective-php/xmldsig#4]

**Comment by jlaraf81** [comment]
Muy agradecido por compartir su proyecto. Me sirvió bastante. Estoy apenas aprendiendo acerca de las firmas en documentos xml. Tengo duda en la parte donde está setReferenceUri(' ').     Que cambió hay que hacer para activarla ?. Es que sale vacía. De antemano Mil gracias

**Comment by odan** [comment]
I don't know what you mean or what the issue is.
